### ISSUE TITLE
Faucet https://faucet.metamask.io doesn't work anymore.

### ISSUE THREAD

**Issue by MatthiasLohr** [MetaMask/eth-faucet#12]
Hey,

is this the repository belonging to https://faucet.metamask.io? Is there a chance to get the Faucet back working?

Best regards
Matthias

**Comment by kumavis** [comment]
hey sorry the infura api we were using expired, should be working again

**Comment by MatthiasLohr** [comment]
No, does not work.

> No web3 detected.
