### ISSUE TITLE
Error: MetaMask Tx Signature: User denied transaction signature. persists after successful withdrawal

### ISSUE THREAD

**Issue by MariusVanDerWijden** [MetaMask/eth-faucet#13]
Hey guys, 
thank you for providing the faucet! 

I just found a really small issue. If you try to send money to the faucet, and then decline the signature, the faucet outputs "Error: MetaMask Tx Signature: User denied transaction signature." if you then request some ether, the error message persists. 

#### Expected behavior
Expected behavior would be that the error message would go away after I successfully redeemed ether after an error.

**Comment by kumavis** [comment]
finally fixed, thanks :wrench:
