### ISSUE TITLE
Unable to get Ether from faucet

### ISSUE THREAD

**Issue by eugeniuLivandovschi** [MetaMask/eth-faucet#24]
https://faucet.metamask.io/
Unable to get ether 
address: 0x217b7e15afe0cd4a6eaac88b930f7fa3e0874643
{"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:52:23)\\n at Proxy.eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:54:11)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\\n at Request.self.callback (/www/node_modules/request/request.js:186:22)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\\n at Proxy.emit (events.js:310:20)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\\n at Request.eval (/www/node_modules/request/request.js:1155:10)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\"}}'"}

**Comment by kumavis** [comment]
i setup stronger rate limiting to keep out the spammers
