### ISSUE TITLE
Replacement Transaction Underpriced

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/eth-faucet#26]
Migrated from https://github.com/MetaMask/metamask-extension/issues/10210

I am not able to get test ethers from Ropsten faucet. It either shows some error or the transaction hash is not available on ropsten etherscan.

**Steps to reproduce (REQUIRED)**

1. Go to metamask extension
2. Click on buy and then click on add ethers from faucet
3. If the screen gives a TxHash, then it is not available on etherscan. If no TxHash is shown, then It gives "Replacement Transaction Underpriced" error

**Expected behavior**
Test ethers should have been credited to account.

**Screenshots**
![Screenshot from 2021-01-19 08-56-20](https://user-images.githubusercontent.com/77089409/104984484-c849a180-5a34-11eb-85ee-fe5b27cbd728.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Brave Browser Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)
 - MetaMask Version: v8.1.11

**Additional context (Error Messages, etc.)**
I have tried resetting my account and even reinstalled the metamask extension. But none of the methods work.
>>>

**Comment by meijdenmedia** [comment]
Hi guys,

I tried to perform some transactions today and those where stuck in 'queue'.
After a couple of hours I deleted the extension and retried.

Now I'm getting this error.

How can I get my account and coins back? :(

> Swap failed: replacement fee too low (error={"code":-32603,"message":"Error: [ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}}'","stack":"Error: Error: [ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}}'"}, method="sendTransaction", transaction=undefined, code=REPLACEMENT_UNDERPRICED, version=providers/5.0.19)
